---
settings:
  name: ONTAP tools for VMware vSphere 10.0
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-tw,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn
sidebar:
  entries:
  - title: 適用於 VMware vSphere 10.0 文件的 ONTAP 工具
    url: "/index.html"
  - title: 版本資訊
    url: "/release_notes.html"
  - section: concepts
  - section: deploy
  - section: configure
  - section: manage
  - section: migrate
  - title: 法律聲明
    url: "/legal-notices.html"
